fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    from_email: 
        address: "%mailer_user%"
        sender_name: "thunderman"
    resetting:
        email:
            from_email:
                address:      testwf33@gmail.com
                sender_name:  "thunderman"
                
    registration:
        confirmation: 
            enabled: true          
            template:  '@FOSUser/Registration/email.txt.twig' 
        
